name: Call Reusable workflow

on: 
  workflow_dispatch:
    inputs:
      configuration:
         description: 'Configuration'
         required: true
         default: 'true'
         
jobs:
   call_reusable:
     uses: ./.github/workflows/Reusable_workflow.yml
     with:
         configuration: ${{ github.event.inputs.configuration }}
   job2:
     runs-on: ubuntu-latest
     needs: call_reusable
     steps:
      - run: echo ${{ needs.job1.outputs.firstword }}
