name: Call Reusable workflow

on: 
  workflow_dispatch:
    inputs:
      config-path:
         description: 'Configuration'
         required: true
jobs:
   call_reusable:
     runs-on: ubuntu-latest
     steps:
      - name: Caller
        uses: ./.github/workflows/Reusable_workflow.yml
        with:
         config-path: ${{ github.event.inputs.config-path }}
    
