name: Canceled Workflow
on:
 workflow_dispatch:
   
jobs:
 Print:
   runs-on: ubuntu-latest

   steps:
   - name: Print Hello World
     run: exit 1
 Configure: 
   needs: Print
   runs-on: ubuntu-latest
   if: ${{ always() }}
   steps:
   - name: Prepare Configuration
     run: echo "Job 2 executed ALWAYS."
