name: EnvironmentSetup Job
on:
 workflow_dispatch:
   inputs:
     Configuration:
       type: string
       description: 'Configuration'
       required: true
       default: 'release'
jobs:
  development:
    if: ${{inputs.Configuration != 'release' }}
    uses: ./.github/workflows/Environment_Message.yml
    with:
      configuration: ${{ inputs.configuration }}
  production:
    if: ${{inputs.Configuration == 'release' }}
    uses: ./.github/workflows/Environment_Message.yml
    with:
      configuration: ${{ inputs.configuration }}

  job2:
    runs-on: ubuntu-latest
    needs: [production,development]
    steps:
      - name: Check Conclusion
        run: |
         build_conclusion="${{ steps.job2.outputs.bmconclusion }}"
         upload_conclusion="${{ steps.job2.outputs.umconclusion }}"
         process_conclusion="${{ steps.job2.outputs.pmconclusion }}"
         if [ "$build_conclusion" == "success" ] && [ "$upload_conclusion" == "success" ] && [ "$process_conclusion" == "success" ]; then
           echo "Overall Status: SUCCESS"
         else
           echo "Overall Status: FAILURE"
         fi
