name: EnvironmentSetup Job
on:
 workflow_dispatch:
   inputs:
     Configuration:
       description: 'Configuration'
       required: false
       default: 'release'
jobs:
  production:
    runs-on: ubuntu-latest    
    if: ${{inputs.Configuration}} == "release" 
    environment: Production
    steps:
     - name: EnvironmentSetup1
       run: |
           echo "Setting environment to Production"
           echo "MY_ENVIRONMENT=Production" >> $GITHUB_ENV
  development:
    needs: production
    runs-on: ubuntu-latest    
    if: ${{ failure() }}
    steps:
     - name: EnvironmentSetup2
       run: |
           echo "Setting environment to Production"
           echo "MY_ENVIRONMENT=Production" >> $GITHUB_ENV
     
