name: Environment Message

on:
  workflow_call:
   inputs:
     Configuration:
        type: string
        description: 'Environment Setup'
        required: true 
        default: 'release'
jobs:
   build_message:
       runs-on: ubuntu-latest
       outputs:
         bmconclusion: ${{ steps.build_message.outcome }}
       steps:
        - name: Build Message
          run: |
             echo "Building Message....."
   upload_message:
       runs-on: ubuntu-latest
       if: ${{inputs.Configuration == 'release' }}
       environment: production
       needs: build_message
       outputs:
         umconclusion: ${{ steps.upload_message.outcome }}
       steps:
        - name: Upload Message
          run: |
             echo "Uploading Message....."
   upload:
       runs-on: ubuntu-latest
       needs: build_message
       outputs:
         umconclusion: ${{ steps.upload_message.outcome }}
       steps:
        - name: Upload Message
          run: |
             echo "Uploading Message....."
   process_message:
       runs-on: ubuntu-latest
       needs: upload_message
       outputs:
         pmconclusion: ${{ steps.process_message.outcome }}
       steps:
        - name: Build Message
          run: |
             echo "process Message....."
