name: EnvironmentSetup Job
on:
 workflow_dispatch:
   inputs:
     Configuration:
       description: 'Configuration'
       required: false
       default: 'release'
jobs:
  development:
    runs-on: ubuntu-latest  
    if: ${{inputs.Configuration != 'release' }}
    steps:
     - name: EnvironmentSetup
       run: echo "Setting environment to development"
  production:
    runs-on: ubuntu-latest 
    needs: development
    environment: Production
    steps:
     - name: EnvironmentSetup2
       if: ${{ failure() }}
       run: echo "Setting environment to Production" 
     
