name: Environment Message

on:
  workflow_call:
   inputs:
     config:
        type: string
        description: 'Environment Setup'
        required: true 
        default: 'release'
jobs:
   build_message:
       runs-on: ubuntu-latest
       steps:
        - name: Build Message
          run: |
             Echo "Building Message....."
   upload_message:
       runs-on: ubuntu-latest
       environment: production
       needs: build_message
       steps:
        - name: Upload Message
          run: |
             Echo "Uploading Message....."
   process_message:
       runs-on: ubuntu-latest
       needs: upload_message
       steps:
        - name: Build Message
          run: |
             Echo "process Message....."
