name: Environment Result Status
on:
  workflow_call:
   inputs:
     Configuration:
        type: string
        description: 'Environment Setup'
        required: true 
        default: 'release'
jobs:
 status_Update:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Get Message workflow Result
        id: result
        run: |
         echo "Getting Message Workflow Result....." 
         if[ ${{ github.event.workflow_run.conclusion }} == 'Success' ]
          echo "::set-output name=status::success"
         if[ ${{ github.event.workflow_run.conclusion }} == 'failure' ]
          echo "::set-output name=status::failure"
         else
          echo "::set-output name=status::cancelled"
         fi
 update_Status:
  runs-on: ubuntu-latest
  needs: status_Update
  steps:
    - name: Status Report
      run: |
        status="${{ needs.status_update.outputs.status }}"
        if [ "$status" == "Success" ]
         echo "Build, Upload and Process all succeeded."
        if [ "$status" == "failure" ] 
         echo "Failed to process."
        else 
         echo "Workflow Cancelled."
