name: EnvironmentSetup Job
on:
 workflow_dispatch:
   inputs:
     Configuration:
       type: string
       description: 'Configuration'
       required: true
       default: 'release'
jobs:
  development:
    if: ${{inputs.Configuration != 'release' }}
    uses: ./.github/workflows/Environment_Message.yml
    with:
      configuration: ${{ inputs.configuration }}
  production:
    if: ${{inputs.Configuration == 'release' }}
    uses: ./.github/workflows/Environment_Message.yml
    with:
      configuration: ${{ inputs.configuration }}

  Development_status:
    runs-on: ubuntu-latest
    needs: [development]
    steps:
      - name: Check Conclusion
        run: |
         build_conclusion="${{ steps.development.outputs.bmconclusion }}"
         upload_conclusion="${{ steps.development.outputs.uconclusion }}"
         process_conclusion="${{ steps.development.outputs.pconclusion }}"
         if [ "$build_conclusion" == "success" ] && [ "$upload_conclusion" == "success" ] && [ "$process_conclusion" == "success" ]; then
           echo "Overall Status: SUCCESS"
         else
           echo "Overall Status: FAILURE"
         fi
  Production_status:
    runs-on: ubuntu-latest
    needs: [production]
    steps:
      - name: Check Conclusion
        run: |
         build_conclusion="${{ steps.production.outputs.bmconclusion }}"
         upload_conclusion="${{ steps.production.outputs.umconclusion }}"
         process_conclusion="${{ steps.production.outputs.pmconclusion }}"
         if [ "$build_conclusion" == "success" ] && [ "$upload_conclusion" == "success" ] && [ "$process_conclusion" == "success" ]; then
           echo "Overall Status: SUCCESS"
         else
           echo "Overall Status: FAILURE"
         fi
