name: EnvironmentSetup Job
on:
 workflow_dispatch:
   inputs:
     Configuration:
       description: 'Configuration'
       required: false
       default: 'release'
jobs:
  set-environment:
    runs-on: ubuntu-latest    
    if: ${{inputs.Configuration }}" == "release"
    environment: Production
    steps:
     - name: EnvironmentSetup
       run: |
           echo "Setting environment to Production"
           echo "MY_ENVIRONMENT=Production" >> $GITHUB_ENV
    else: ${{inputs.Configuration }}" != "release"
    steps:
     - name: EnvironmentSetup
       run: |
           echo "Setting environment to development"
           echo "MY_ENVIRONMENT=" >> $GITHUB_ENV
     
