name: Environment Message

on:
  workflow_call:
   inputs:
     Configuration:
        type: string
        description: 'Environment Setup'
        required: true 
        default: 'release'
   outputs:
     bmconclusion:
        value: ${{ jobs.build_message.outputs.bmconclusion }}   
     umconclusion:
        value: ${{ jobs.upload_message.outputs.umconclusion }} 
     pmconclusion:
        value: ${{ jobs.process_message.outputs.pmconclusion }} 
     uconclusion:
        value: ${{ jobs.upload.outputs.uconclusion }} 
     pconclusion:
        value: ${{ jobs.process.outputs.pconclusion }} 
jobs:
   build_message:
       runs-on: ubuntu-latest
       outputs:
         bmconclusion: ${{ steps.build.outputs.bmconclusion }}
       steps:
        - id: build
          run:  |
             echo "Building Message....."
             echo "bmconclusion=success" >> $GITHUB_OUTPUT
   upload_message:
       runs-on: ubuntu-latest
       if: ${{inputs.Configuration == 'release' }}
       environment: production
       needs: build_message
       outputs:
         umconclusion: ${{ steps.UploadMessage.outputs.umconclusion }}
       steps:
        - id: UploadMessage
          run: |
             echo "Uploading Message....."
             echo "umconclusion=success" >> $GITHUB_OUTPUT
   upload:
       runs-on: ubuntu-latest
       if: ${{inputs.Configuration != 'release' }}
       needs: build_message
       outputs:
         uconclusion: ${{ steps.Upload.outputs.uconclusion }}
       steps:
        - id: Upload
          run: |
             echo "Uploading Message....."
             echo "uconclusion=success" >> $GITHUB_OUTPUT
   process_message:
       runs-on: ubuntu-latest
       needs: upload_message
       outputs:
         pmconclusion: ${{ steps.ProcessMessage.outputs.pmconclusion }}
       steps:
        - id: ProcessMessage
          run: |
             echo "process Message....."
             echo "pmconclusion=success" >> $GITHUB_OUTPUT
   process:
       runs-on: ubuntu-latest
       needs: upload
       outputs:
         pconclusion: ${{ steps.Process.outputs.pconclusion }}
       steps:
        - id: Process
          run: |
             echo "process Message....."
             echo "pconclusion=success" >> $GITHUB_OUTPUT
          
