name: EnvironmentSetup Job
on:
 workflow_dispatch:
   inputs:
     Configuration:
       description: 'Configuration'
       required: false
       default: 'release'
jobs:
  development:
    runs-on: ubuntu-latest  
    if: ${{inputs.Configuration != 'release' }}
    steps:
     - name: EnvironmentSetup
       run: echo "Setting environment to development"
  production:
    if: ${{inputs.Configuration == 'release' }}
    runs-on: ubuntu-latest 
    environment: Production
    steps:
     - name: EnvironmentSetup2
       run: echo "Setting environment to Production" 
     
