name: Environment Message

on:
  workflow_call:
   inputs:
     Configuration:
        type: string
        description: 'Environment Setup'
        required: true 
        default: 'release'
   outputs:
     bmconclusion:
        value: ${{ jobs.build_message.outputs.bmconclusion }}   
     umconclusion:
        value: ${{ jobs.upload_message.outputs.umconclusion }} 
     pmconclusion:
        value: ${{ jobs.process_message.outputs.pmconclusion }} 
     uconclusion:
        value: ${{ jobs.upload.outputs.uconclusion }} 
     pconclusion:
        value: ${{ jobs.process.outputs.pconclusion }} 
jobs:
   build_message:
       runs-on: ubuntu-latest
       outputs:
         bmconclusion: ${{ steps.build_message.outcome }}
       steps:
        - name: Build Message
          run: |
             echo "Building Message....."
   upload_message:
       runs-on: ubuntu-latest
       if: ${{inputs.Configuration == 'release' }}
       environment: production
       needs: build_message
       outputs:
         umconclusion: ${{ steps.upload_message.outcome }}
       steps:
        - name: Upload Message
          run: |
             echo "Uploading Message....."
   upload:
       runs-on: ubuntu-latest
       if: ${{inputs.Configuration != 'release' }}
       needs: build_message
       outputs:
         uconclusion: ${{ steps.upload.outcome }}
       steps:
        - name: Upload Message
          run: |
             echo "Uploading Message....."
   process_message:
       runs-on: ubuntu-latest
       needs: upload_message
       outputs:
         pmconclusion: ${{ steps.process_message.outcome }}
       steps:
        - name: Build Message
          run: |
             echo "process Message....."
   process:
       runs-on: ubuntu-latest
       needs: upload
       outputs:
         pconclusion: ${{ steps.process.outcome }}
       steps:
        - name: Build Message
          run: |
             echo "process Message....."
          
