name: Environment Message

on:
  workflow_call:
   inputs:
     Configuration:
        type: string
        description: 'Environment Setup'
        required: true 
        default: 'release'
jobs:
   build_message:
       runs-on: ubuntu-latest
       steps:
        - name: Build Message
          run: |
             echo "Building Message....."
   upload_message:
       runs-on: ubuntu-latest
       environment: production
       needs: build_message
       steps:
        - name: Upload Message
          run: |
             echo "Uploading Message....."
   process_message:
       runs-on: ubuntu-latest
       needs: upload_message
       steps:
        - name: Build Message
          run: |
             echo "process Message....."
   status_message:
       if: ${{ failure() || success() }}
       needs: [build_message,upload_message,process_message]
       uses: ./.github/workflows/Environment_Status.yml
       with:
          configuration: ${{ inputs.configuration }}
