name: EnvironmentSetup Job
on:
 workflow_dispatch:
   inputs:
     Configuration:
       description: 'Configuration'
       required: false
       default: 'release'
jobs:
  development:
    runs-on: ubuntu-latest    
    if: "${{inputs.Configuration }} != release"
    steps:
     - name: EnvironmentSetup1
       run: |
           echo "Setting environment to development"
  production:
    runs-on: ubuntu-latest 
    needs: development
    if: "${{ inputs.Configuration }} == release"
    environment: Production
    steps:
     - name: EnvironmentSetup2
       run: |
           echo "Setting environment to Production" 
     
