name: EnvironmentSetup
on:
 workflow_dispatch:
   inputs:
     Configuration:
       type: string
       description: 'Configuration'
       required: true
       default: 'release'
jobs:
  development:
    runs-on: ubuntu-latest  
    if: ${{inputs.Configuration != 'release' }}
    steps:
     - name: EnvironmentSetup
       run: echo "Setting environment to development"
  production:
    runs-on: ubuntu-latest  
    if: ${{inputs.Configuration == 'release' }}
    environment: production
    steps:
     - name: EnvironmentSetup
       run: echo "Setting environment to development"
