name: EnvironmentSetup Job
on:
 workflow_dispatch:
   inputs:
     Configuration:
       description: 'Configuration'
       required: false
       default: 'release'
jobs:
 set-environment:
    runs-on: ubuntu-latest    
    steps:
     - name: EnvironmentSetup
       run: |
         if [ "${{inputs.Configuration }}" == "release" ]; then
           echo "Setting environment to Production"
           echo "MY_ENVIRONMENT=Production" >> $GITHUB_ENV
         else
           echo "No environment set"
           echo "MY_ENVIRONMENT=" >> $GITHUB_ENV
         fi
    environment: $MY_ENVIRONMENT
     
