name: EnvironmentSetup Job
on:
 workflow_dispatch:
   inputs:
     Configuration:
       type: string
       description: 'Configuration'
       required: true
       default: 'release'
jobs:
  development:
    runs-on: ubuntu-latest  
    if: ${{inputs.Configuration != 'release' }}
    steps:
     - name: EnvironmentSetup
       run: echo "Setting environment to development"
  production:
    if: ${{inputs.Configuration == 'release' }}
    uses: ./.github/workflows/Environment_Message.yml
    with:
      configuration: ${{ inputs.configuration }}

  job2:
    runs-on: ubuntu-latest
    needs: production
    steps:
      - name: Check Conclusion
        run: |
         build_conclusion="${{ steps.call_message_workflow.outputs.build_message_conclusion }}"
         upload_conclusion="${{ steps.call_message_workflow.outputs.upload_message_conclusion }}"
         process_conclusion="${{ steps.call_message_workflow.outputs.process_message_conclusion }}"
         if [ "$build_conclusion" == "success" ] && [ "$upload_conclusion" == "success" ] && [ "$process_conclusion" == "success" ]; then
           echo "Overall Status: SUCCESS"
         else
           echo "Overall Status: FAILURE"
         fi
