name: Combined Job failCase
on:
 workflow_dispatch:

jobs:
 Print:
   runs-on: ubuntu-latest 
   steps:
   - name: Print Hello World
     run: |
          echo "This is Job 1"
          exit 1
 Configure:
   needs: Print
   runs-on: ubuntu-latest
   
   steps:
   - name: Check Print status
     id: job1_status
     run: echo "Job 1 succeeded"
   - name: Prepare Configuration
     if: ${{ steps.job1_status.outcome == 'failure' }}
     run: echo "Job 2"
