name: Combined Job
on:
 workflow_dispatch:
   inputs:
     Configuration:
       description: 'Configuration'
       required: true
       default: 'Hello'
     ConfigCode:
       description: 'ConfigCode'
       required: false
     ConfigType:
       description: 'ConfigType'
       required: true
       default: 'Prod'
       options:
         - 'Staging'
         - 'Prod'
         - 'QA'

jobs:
 configure_Print:
   runs-on: ubuntu-latest

   steps:
   - name: Print Hello World
     run: echo "Hello World"
   
   - name: Prepare Configuration
     run: |
       formattedConfig="${{ inputs.configuration }} , "
       if [[ -n "${{ inputs.configCode }}" ]]; then
       formattedConfig= $formattedConfig"${{ inputs.configCode }} ,"
       else
       formattedConfig= $formattedConfig
       fi
       formattedConfig= $formattedConfig"${{ inputs.configType }}"
       echo "Formatted Configuration: $formattedConfig"
