name: Job2
on:
 workflow_dispatch:
   inputs:
     configuration:
       description: 'Configuration'
       required: true
       default: 'Hello'
     configCode:
       description: 'ConfigCode'
       required: false
       default: '10'
     configType:
       description: 'ConfigType'
       required: true
       default: 'Prod'
       options:
         - 'Staging'
         - 'Prod'
         - 'QA'

jobs:
 configure:
   runs-on: ubuntu-latest

   steps:
   - name: Prepare Configuration
     id: config
     run: |
       if [[ -n "$configCode" ]]; then
         formattedConfig="$configuration, $configCode, $configType"
       else
         formattedConfig="$configuration, $configType"
       fi
       echo "Formatted Configuration: $formattedConfig"
