name: Combined Job cancelled
on:
 workflow_dispatch:
  inputs:
   cancelWorkflow:
     description: 'Cancel Workflow'
     required: false
     default: false
   
jobs:
 Print:
   runs-on: ubuntu-latest 
   steps:
   - name: Print Hello World
     run: |
          echo "This is Job 1"
          exit 1
 Configure:
      needs: Print
      runs-on: ubuntu-latest
      if: ${{ cancelled() }}
      steps:
      - name: Prepare Configuration
        if: ${{ github.event.inputs.cancelWorkflow == 'true' }}
        run: echo "##vso[task.setvariable variable=workflow_cancelled]true"
        
      - name: Workflow Cancelled
        if: ${{ env.workflow_cancelled == 'true' }}
        run: echo "JOB 2 when workflow is cancelled."
