name: Combined Job cancelled
on:
 workflow_dispatch:
 
jobs:
 Print:
   runs-on: ubuntu-latest 
   steps:
   - name: Print Hello World
     run: |
          echo "This is Job 1"
          exit 1
 Configure:
      needs: Print
      runs-on: ubuntu-latest
      if: ${{ cancelled() }}
      steps:
      - name: Prepare Configuration
        run: echo "JOB 2 when workflow is cancelled."
