name: EnvironmentSetup Job
on:
 workflow_dispatch:
   inputs:
     Configuration:
       type: string
       description: 'Configuration'
       required: true
       default: 'release'
jobs:
  development-production:
    uses: ./.github/workflows/reuseableworkflowtrail.yml
    with:
      configuration: ${{ inputs.configuration }}
  
  status:
     if: ${{ always() }}
     runs-on: ubuntu-latest
     needs: development-production
     steps: 
       - name: Success
         if: ${{ success() && steps.development-production.conclusion == 'success' }}
         run: 
          echo "The workflow was Success."
       - name: failure
         if: ${{ steps.development-production.conclusion == 'failure' }}
         run: 
          echo "The workflow was failure."
       - name: Cancelled
         if: ${{ cancelled() && steps.development-production.conclusion == 'cancelled' }}
         run: 
          echo "The workflow was cancelled."
