name: EnvironmentSetup Job
on:
 workflow_dispatch:
   inputs:
     Configuration:
       type: string
       description: 'Configuration'
       required: true
       default: 'release'
jobs:
  development-production:
    uses: ./.github/workflows/reuseableworkflowtrail.yml
    with:
      configuration: ${{ inputs.configuration }}
  
  status:
     if: ${{ always() }}
     runs-on: ubuntu-latest
     needs: development-production
     steps: 
       - name: Success
         if: ${{ steps.development-production.outputs.process_development == 'success' || 
               steps.development-production.outputs.process_production == 'success'}} 
         run: 
          echo "The workflow was Success."
       - name: failure
         if: ${{ steps.development-production.outputs.process_development == 'failure' || 
               steps.development-production.outputs.process_production == 'failure'}} 
         run: 
          echo "The workflow was failed."
       - name: Cancelled
         if: ${{ steps.development-production.outputs.process_development == 'cancelled' || 
               steps.development-production.outputs.process_production == 'cancelled'}} 
         run: 
          echo "The workflow was cancelled."
