name: EnvironmentSetup Job
on:
 workflow_dispatch:
   inputs:
     Configuration:
       type: string
       description: 'Configuration'
       required: true
       default: 'release'
jobs:
  development-production:
       uses: ./.github/workflows/reuseableworkflowtrail.yml
       with:
          configuration: ${{ inputs.configuration }}
  
  failure_status:
     runs-on: ubuntu-latest
     needs: development-production
     if: failure()
     steps: 
       - name: failure
         run: 
          echo "The workflow was failure."
  success_status:
     runs-on: ubuntu-latest
     needs: development-production
     if: success()
     steps: 
       - name: Success
         run: 
          echo "The workflow was Success."
  cancelled_status:
     runs-on: ubuntu-latest
     needs: development-production
     if: cancelled()
     steps: 
       - name: cancelled
         run: 
          echo "The workflow was cancelled."        
