name: EnvironmentSetup Job
on:
 workflow_dispatch:
   inputs:
     Configuration:
       type: string
       description: 'Configuration'
       required: true
       default: 'release'
jobs:
  development-production:
    uses: ./.github/workflows/reuseableworkflowtrail.yml
    with:
      configuration: ${{ inputs.configuration }}
  status:
     runs-on: ubuntu-latest
     steps: 
       - name: Success
         if: ${{ success('development-production') }}
         run: 
          echo "The workflow was Success."
       - name: failure
         if: ${{ failure('development-production') }}
         run: 
          echo "The workflow was failure."
       - name: Cancelled
         if: ${{ cancelled('development-production') }}
         run: 
          echo "The workflow was cancelled."
