name: New Branch Workflow

on:
 push:
   branches:
     - '*'
jobs:
 build:
   runs-on: ubuntu-latest
   if: startsWith(github.ref,'refs/heads/release')
   steps: 
      - run: echo "execute when new branch is created like release-* or fix-*"
