name: New Branch Workflow

on:
 create:
   branches:
     - '*'
jobs:
 build:
   runs-on: ubuntu-latest
   if: startsWith(github.ref,'refs/heads/release') || startsWith(github.ref,'refs/heads/fix')
   steps: 
      - run: echo "execute when new branch is created like release-* or fix-*"
