name: Reusable workflow

on:
  workflow_call:
    inputs:
      configuration:
        description: 'Configuration'
        required: true
        type: string
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.Reusable-workflow.outputs.output1 }}
jobs:
  Reusable-workflow:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
    steps:
     - name: set Output1
       id: step1
       run: |
        if: ${{ input.configuration }} == 'true'; then
        echo "firstword=hello_world_true" >> "$GITHUB_OUTPUT"
        else
        echo "firstword=hello_world_false" >> "$GITHUB_OUTPUT"
        fi
