name: Call Reusable workflow

on: 
  workflow_dispatch:
    inputs:
     configuration: 
        type: boolean
        required: true      
         
jobs:
   call_reusable:
     runs-on: ubuntu-latest
     steps: |
      - uses: ./.github/workflows/Reusable_workflow.yml
        with:
            configuration: ${{ inputs.configuration }}
        run: echo "${{ needs.call_reusable.outputs.firstword }}"
