name: Reusable workflow

on:
  workflow_call:
    inputs:
      config-path:
        description: Reusable-workflow
        required: true
        default: 'true'
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        configuration-path: ${{ inputs.config-path }}
