name: Reusable workflow

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string

jobs:
  Reusable-workflow:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
     - name: set Output1
       id: step1
       run: |
        if: ${{ input.config-path }} == true; then
        echo "::set-output name=test:: Hello World True"
        else
        echo "::set-output name=test:: Hello World False"
        
