name: Reusable workflow

on:
  workflow_call:
    inputs:
      configuration:
        description: 'Configuration'
        required: true
        type: string

jobs:
  Reusable-workflow:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
     - name: set Output1
       id: step1
       run: |
        if: ${{ input.configuration }} == true; then
        echo "test=hello world true" >> "$GITHUB_OUTPUT"
        else
        echo "test=hello world false" >> "$GITHUB_OUTPUT"
        fi
