name: Call Reusable workflow

on: 
  workflow_dispatch:
    inputs:
     configuration: 
        type: boolean
        required: true      
         
jobs:
   call_reusable:
     uses: ./.github/workflows/Reusable_workflow.yml
     with:
         configuration: ${{ inputs.configuration }}
     
   job2:
    runs-on: ubuntu-latest
    needs: call_reusable
    steps:
      - run: echo "${{ needs.call_reusable.outputs.firstword }}"
