name: Environment Message

on:
  workflow_call:
   inputs:
     Configuration:
        type: string
        description: 'Environment Setup'
        required: true 
        default: 'release'
jobs:
   build_message:
       runs-on: ubuntu-latest
       steps:
        - id: build-message
          run:  |
             echo "Building Message....."
        - name: build
          run: |
             echo "Build"
             exit 2
   upload_production:
       runs-on: ubuntu-latest
       if: ${{ inputs.Configuration == 'release' }}
       environment: production
       needs: build_message
       steps:
        - id: UploadMessage
          run: |
             echo "Uploading Message....."
   upload_development:
       runs-on: ubuntu-latest
       if: ${{inputs.Configuration != 'release' }}
       needs: build_message
       steps:
        - id: UploadMessage
          run: echo "Uploading Message....."
        - id: Upload-Message
          run: echo "Upload"
   process_development:
       runs-on: ubuntu-latest
       needs: upload_development
       steps:
        - id: ProcessMessage
          run: |
             echo "pmconclusion=success" >> $GITHUB_OUTPUT
        - id: Process
          run: |
             echo "process Message....."
   process_production:
       runs-on: ubuntu-latest
       needs: upload_production
       steps:
        - id: ProcessMessage
          run: echo "process Message....."
        - id: Process
          run: echo "process Message....."
