name: Caller Workflow
on:
 workflow_dispatch:
   inputs:
     configuration:
       description: 'Configuration'
       required: true
jobs:
 call_reusable:
   runs-on: ubuntu-latest
   steps:
     - name: Call Reusable Workflow
       uses: ./.github/workflows/reusable.yml
       with:
         configuration: ${{ github.event.inputs.configuration }}
     - name: Display Output
       run: echo "Reusable Workflow Output:${{ steps.call_reusable.outputs.hello_output }}"
