name: Canceled Workflows
on:
 workflow_dispatch:
   
jobs:
 JOB1:
   runs-on: ubuntu-latest

   steps:
   - name: JOB 1
     run: exit 1
 JOB2: 
   needs: JOB1
   runs-on: ubuntu-latest
   if: ${{ always() }}
   steps:
   - name: Prepare Configuration
     run: echo "Job 2 executed ALWAYS."
