name: step 1 - Cancelled Workflow

on:
  workflow_dispatch:
    inputs:
      cancel:
        description: 'Cancel the main workflow'
        required: true
        default: 'false'

jobs:
  cancel_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Workflow
        if: ${{ github.event.inputs.cancel == 'true' }}
        run: echo "Cancelling the main workflow"
